yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group/<slug:slug>/', views.group_posts, name = 'group_posts'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True) 
    description = models.TextField()   
    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    ) 
    group = models.ForeignKey(Group, blank=True, null=True, on_delete=models.SET_NULL, related_name='posts')
    

yatube/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, Group
from django.shortcuts import render, get_object_or_404

# Главная страница
def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 


# Страница с информацией об публикациях;
# view-функция принимает параметр slug из path()
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_posts.html', context) 

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru"> 
{% load static %}    
  <head>  
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    {% block title %} 
          
    {% endblock %} 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Лев Толстой – зеркало русской революции.</title>  
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Место для основного блока
        {% endblock content %}
      </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
{% load static %} 
  <class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">© 2020 Copyright 
    <p><span style="color:red">Ya</span>tube</p> 
  </div>    

yatube/templates/includes/header.html
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      {% load static %} 
      <header>
        <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
        <!-- В дальнейшем тут будет создано полноценное меню -->    
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
          <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
              <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
              <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
              <span style="color:red">Ya</span>tube
            </a>
          </div>
        </nav>      
      </header>

yatube/templates/posts/group_list.html
<<!DOCTYPE html> 
<html lang="ru"> 
{% extends 'base.html' %}
{% block title %} 
  Последние посты в группе {{ group_title }}
{% endblock title %} 
{% block content %}
  <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>  
      {% for post in posts %}
        </article>
          <ul> 
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы {{ posts.group_title }}</a>
            {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
{% endblock %}  

yatube/templates/posts/group_posts.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} 
  Последние посты в группе {{ group_title }}
{% endblock title %} 
{% block content %}
  <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>  
      {% for post in posts %}
        </article>
          <ul> 
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы {{ posts.group_title }}</a>
            {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
{% endblock %}  
  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}  
{% block content %}
  <h1> Последние обновления на сайте </h1>
    {% for post in posts %}
      </article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы {{ posts.group_title }}</a
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
    </article>
  {% endfor %} 
{% endblock %}

  